### ISSUE TITLE
Teamfarben [Vorschlag]

### ISSUE THREAD

**Issue by penguinized** [Mimoja/HookWars#1]
Sinn: Teams UND einzelne Spielfiguren EINFACH unterscheidbar machen.
Vorschlag: 
Jede Figur des einen Teams bekommt einen eindeutigen (am besten gut unterscheidbaren) Farbton aus dem Blau/Grün-Farbbereich.
Jede Figur des Anderen Teams bekommt einen eindeutigen (am besten gut unterscheidbaren) Farbton aus dem Gelb/Rot-Farbbereich.

**Comment by Mimoja** [comment]
Shader unterstützt das jetzt. Kann nun einfach implementiert werden
