### ISSUE TITLE
Last patch broke rotation and hooks

### ISSUE THREAD

**Issue by penguinized** [Mimoja/HookWars#2]
So. Ihr habts mal wieder kaputt gemacht. 
Die Rotation stimmt überhaupt nicht mit dem R-Stick überein, und hat nur noch nach rechts, nach links und nach unten. Und der Hook kann überhaupt nicht mehr gefeuert werden. Keine Kaufempfehlung.

**Comment by penguinized** [comment]
Hm. frühere Commits funktionieren diesbezüglich auch nicht mehr :\ Wie siehts bei dir aus?

**Comment by penguinized** [comment]
Was für ein Bullshit. Mein Gerät gibt anscheinend grade die Achsen des rechten Sticks an rechten Stick (vertikal) und linken Trigger?! wtf.

**Comment by Mimoja** [comment]
:D:D:D
